# Generated by Django 2.2.5 on 2019-10-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
